import './style.css';

/* import the initial page-load function */
import initialPageLoad from './home.js';

// calls the function
initialPageLoad();

/* 1-1. ran npm init in my project directory to generate a packge.json file
        created a directory, initialized npm (basic setup)

   1-2. ran npm install wepack webpack-cli save-dev into install webpack to the node_modules directory
        installed webpack locally, and installed the tool used to run webpack on the command line
        (basic setup)

   1-2*.added a .gitignore file to my project so that I don't have to sync the contents of node_modules
        to github; the dependencies that are stored there can be installed from my package.json by running
        npm install 
      
   1-3. created a src and dist directory
        1-3-1. created an index.js file in src (basic setup)
        1-3-2. created an index.html file in dist (basic setup); link main.js file in a script tag
               main.js is the file generated by webpack
        1-3-3. created a webpack.config.js file 

   3.   wrote a simple console.log statement and then ran npx webpack, loaded up dist/index.html in
        a browser and made sure everything is working correctly

   3*.  ran npx webpack --watch, so that I won't have to rerun webpack every time I make a change
        
  oyster pancake - round, crispy snack made with a batter of pork, oyster, spring onion, grated cabbage, and rice flour 
  
  taro cake - triangular snack made of ground taro, first steamed and then deep-fried until crispy
  
  Fuzhou pancake - crispy snack with a hole in the middle, made with a batter of sausage, spring onion, and rice flour 

  fried dough - deep-fried strip of wheat flour dough 

  pan-fried buns - buns with a center of seasoned pork, pan-fried

  meat dumpling soup / bian rou - minced pork, ginger, garlic, and spring onion in glutinous rice wrappers in pork broth

  Fuzhou wonton soup - minced pork and shrimp, mushrooms, ginger, and spring onion in silky wheat wrappers in pork broth

  fishball soup - balls made of ground fish paste with a filling of seasoned pork in chicken broth

  clam noodle soup / ding bian hu - clams, dried shrimp, day lily, spring onion, and flat rice noodles in chicken broth

  longevity duck noodle soup - stewed duck, dried razor clam, shitake mushrooms, rice vermicelli noodles, and a hard-boiled egg in duck broth 
  
  duck gizzard noodle soup - stewed duck gizzard, napa cabbage, shanghai bok choy, spring onion, rice vermicelli noodles in duck broth 
  
  rice noodles with pork intestines - pork intestines, scrambled egg, napa cabbage stir fried with thick rice noodles 

  noodles with peanut sauce - ramen noodles over sauce with peanut butter, soy sauce, and sesame oil

  stir fried vermicelli with vegetables and egg - scrambled egg, napa cabbage, celery, onion, and spring onion stir fried with rice vermicelli noodles
  */